export interface LangFile {
  name: string
  section?: boolean
  dot?: string   // 'g' = green, 'a' = amber, 'r' = red
  active?: boolean
}

export interface CodeLine {
  class: string
  text: string
}

export interface LangData {
  id: string
  name: string
  ext: string
  runLabel: string
  termLabel: string
  files: LangFile[]
  code: CodeLine[]
  run: CodeLine[]
}

export const langDataMap: Record<string, LangData> = {
  cedar: {
    id: 'cedar',
    name: 'Cedar Policy IDE', ext: '.cedar', runLabel: '▷ EVALUATE', termLabel: 'CEDAR_EVAL_OUTPUT',
    files: [
      { name: '// policies', section: true },
      { name: 'main.cedar', dot: 'g', active: true },
      { name: 'entities.json', dot: 'a' },
      { name: 'request.json', dot: 'a' },
      { name: '// tests', section: true },
      { name: 'auth_test.json', dot: 'r' },
      { name: 'deny_test.json', dot: 'r' },
      { name: 'edge_cases.json', dot: 'r' },
      { name: '// templates', section: true },
      { name: 'least_priv.cedar', dot: 'g' },
      { name: 'time_based.cedar', dot: 'g' },
      { name: 'mfa_required.cedar', dot: 'g' },
    ],
    code: [
      { class: 'cmt', text: '// Cedar Policy — Least Privilege + Temporal Access Control' },
      { class: 'cmt', text: '// @version 2.4.1  @author alex.kim' },
      { class: '', text: '' },
      { class: 'kw', text: 'permit (' },
      { class: '', text: '  principal in Group::"engineering",' },
      { class: '', text: '  action in [Action::"read", Action::"list"],' },
      { class: '', text: '  resource in Bucket::"prod-data"' },
      { class: '', text: ')' },
      { class: 'kw', text: 'when {' },
      { class: '', text: '  context.mfa_verified == true &&' },
      { class: '', text: '  context.ip_in_allowlist == true &&' },
      { class: '', text: '  principal.clearance_level >= 2' },
      { class: '', text: '};' },
      { class: '', text: '' },
      { class: 'kw', text: 'forbid (' },
      { class: '', text: '  principal,' },
      { class: '', text: '  action == Action::"delete",' },
      { class: '', text: '  resource in Bucket::"prod-data"' },
      { class: '', text: ')' },
      { class: 'kw', text: 'unless {' },
      { class: '', text: '  principal in Group::"admins" &&' },
      { class: '', text: '  context.approval_ticket != "" &&' },
      { class: '', text: '  context.change_window_active == true' },
      { class: '', text: '};' },
    ],
    run: [
      { class: 'mute', text: '$ cedar-policy eval --mode strict' },
      { class: 'mute', text: '──────────────────────────────' },
      { class: 'ok', text: '✓ parsing policies...' },
      { class: 'ok', text: '✓ schema validation PASS' },
      { class: 'info', text: '⟳ running test matrix...' },
      { class: 'mute', text: '  auth_test.json : 4/4 PASS' },
      { class: 'mute', text: '  deny_test.json : 3/3 PASS' },
      { class: 'ok', text: 'PERMIT alice@org → read → prod-data' },
      { class: 'err', text: 'DENY   contractor → delete → prod-data' },
      { class: 'ok', text: 'PERMIT contractor → read → shared (09:41 WED)' },
      { class: 'warn', text: '⚠ WARN policy#15 shadows policy#4' },
      { class: 'mute', text: 'eval_time: 9ms' },
      { class: 'ok', text: 'ALL_TESTS_PASS' },
    ],
  },

  rego: {
    id: 'rego',
    name: 'Rego / OPA IDE', ext: '.rego', runLabel: '▷ OPA EVAL', termLabel: 'OPA_OUTPUT',
    files: [
      { name: '// policies', section: true },
      { name: 'authz.rego', dot: 'g', active: true },
      { name: 'rbac.rego', dot: 'g' },
      { name: '// data', section: true },
      { name: 'users.json', dot: 'a' },
      { name: 'roles.json', dot: 'a' },
      { name: '// tests', section: true },
      { name: 'authz_test.rego', dot: 'r' },
    ],
    code: [
      { class: 'cmt', text: '# OPA / Rego — RBAC Authorization Policy' },
      { class: 'cmt', text: '# package: authz' },
      { class: '', text: '' },
      { class: 'kw', text: 'package authz' },
      { class: '', text: '' },
      { class: 'kw', text: 'import rego.v1' },
      { class: '', text: '' },
      { class: 'cmt', text: '# Default deny all' },
      { class: 'kw', text: 'default allow := false' },
      { class: '', text: '' },
      { class: 'cmt', text: '# Allow if user has required role' },
      { class: 'kw', text: 'allow if {' },
      { class: '', text: '  some role in data.roles[input.user]' },
      { class: '', text: '  role in data.permissions[input.action]' },
      { class: '', text: '}' },
      { class: '', text: '' },
      { class: 'cmt', text: '# Admin bypass' },
      { class: 'kw', text: 'allow if {' },
      { class: '', text: '  data.roles[input.user][_] == "admin"' },
      { class: '', text: '}' },
    ],
    run: [
      { class: 'mute', text: '$ opa eval -d policies/ -d data/ "data.authz.allow"' },
      { class: 'ok', text: '{"result": [{"expressions": [{"value": true}]}]}' },
      { class: 'mute', text: '$ opa test policies/ --verbose' },
      { class: 'ok', text: 'PASS: test_admin_allowed' },
      { class: 'ok', text: 'PASS: test_user_denied_admin_action' },
      { class: 'ok', text: 'PASS: test_viewer_read_allowed' },
      { class: 'ok', text: '3 tests, 0 failures' },
    ],
  },

  json: {
    id: 'json',
    name: 'JSON Editor', ext: '.json', runLabel: '▷ VALIDATE', termLabel: 'JSON_OUTPUT',
    files: [
      { name: '// payloads', section: true },
      { name: 'jwt_payload.json', dot: 'g', active: true },
      { name: 'scim_user.json', dot: 'g' },
      { name: 'oidc_config.json', dot: 'g' },
      { name: '// schemas', section: true },
      { name: 'jwt_schema.json', dot: 'a' },
    ],
    code: [
      { class: 'cmt', text: '// JWT Payload — decoded claims' },
      { class: '', text: '{' },
      { class: '', text: '  "iss": "https://idp.example.com",' },
      { class: '', text: '  "sub": "alice@org",' },
      { class: '', text: '  "aud": "my-app-client-001",' },
      { class: 'num', text: '  "exp": 1738000000,' },
      { class: 'num', text: '  "iat": 1737996400,' },
      { class: '', text: '  "amr": ["pwd", "totp"],' },
      { class: '', text: '  "email": "alice@example.org",' },
      { class: '', text: '  "groups": ["engineering", "iam-admins"]' },
      { class: '', text: '}' },
    ],
    run: [
      { class: 'mute', text: '$ json-validate --schema jwt_schema.json jwt_payload.json' },
      { class: 'ok', text: '✓ valid JSON' },
      { class: 'ok', text: '✓ schema conforms' },
      { class: 'ok', text: '✓ "iss" — uri format ✓' },
      { class: 'ok', text: '✓ "exp" — future timestamp ✓' },
      { class: 'warn', text: '⚠  "email" not in required claims list' },
      { class: 'ok', text: 'validation complete // 1 warning' },
    ],
  },

  javascript: {
    id: 'javascript',
    name: 'JavaScript IDE', ext: '.js', runLabel: '▷ RUN', termLabel: 'JS_CONSOLE',
    files: [
      { name: '// scripts', section: true },
      { name: 'pkce_helper.js', dot: 'g', active: true },
      { name: 'jwt_decode.js', dot: 'g' },
      { name: 'oauth_client.js', dot: 'a' },
      { name: '// tests', section: true },
      { name: 'pkce.test.js', dot: 'r' },
    ],
    code: [
      { class: 'cmt', text: '// PKCE Helper — code_verifier & code_challenge' },
      { class: '', text: '' },
      { class: 'kw', text: 'async function generatePKCE() {' },
      { class: 'cmt', text: '  // 1. Generate 32 random bytes → code_verifier' },
      { class: '', text: '  const bytes = new Uint8Array(32);' },
      { class: '', text: '  crypto.getRandomValues(bytes);' },
      { class: '', text: '' },
      { class: '', text: "  const verifier = btoa(String.fromCharCode(...bytes))" },
      { class: '', text: "    .replace(/\\+/g, '-').replace(/\\//g, '_').replace(/=/g, '');" },
      { class: '', text: '' },
      { class: 'cmt', text: "  // 2. SHA-256 hash → base64url = code_challenge" },
      { class: '', text: '  const encoded = new TextEncoder().encode(verifier);' },
      { class: '', text: "  const hash = await crypto.subtle.digest('SHA-256', encoded);" },
      { class: '', text: '' },
      { class: '', text: '  const challenge = btoa(String.fromCharCode(...new Uint8Array(hash)))' },
      { class: '', text: "    .replace(/\\+/g, '-').replace(/\\//g, '_').replace(/=/g, '');" },
      { class: '', text: '' },
      { class: 'kw', text: '  return ' },
      { class: '', text: '{ verifier, challenge };' },
      { class: '', text: '}' },
    ],
    run: [
      { class: 'mute', text: '$ node pkce_helper.js' },
      { class: 'ok', text: 'code_verifier: dBjftJeZ4CVP-mB92K27uhbUJU1p1r_...' },
      { class: 'ok', text: 'code_challenge: E9Melhoa2OwvFrEMTJguCHaoeK1t8...' },
      { class: 'mute', text: '$ node pkce.test.js' },
      { class: 'ok', text: '✓ verifier is 43–128 chars' },
      { class: 'ok', text: '✓ challenge is base64url' },
      { class: 'ok', text: '✓ challenge == BASE64URL(SHA256(verifier))' },
      { class: 'ok', text: '3/3 tests PASS' },
    ],
  },

  python: {
    id: 'python',
    name: 'Python IDE', ext: '.py', runLabel: '▷ RUN', termLabel: 'PYTHON_OUTPUT',
    files: [
      { name: '// scripts', section: true },
      { name: 'scim_client.py', dot: 'g', active: true },
      { name: 'token_introspect.py', dot: 'g' },
      { name: 'iam_policy_gen.py', dot: 'a' },
    ],
    code: [
      { class: 'cmt', text: '# SCIM 2.0 Client — User provisioning helper' },
      { class: '', text: '' },
      { class: 'kw', text: 'import ' },
      { class: '', text: 'requests' },
      { class: '', text: '' },
      { class: 'kw', text: 'class ' },
      { class: '', text: 'SCIMClient:' },
      { class: '', text: '    def __init__(self, base_url: str, token: str):' },
      { class: '', text: '        self.base_url = base_url' },
      { class: '', text: '        self.headers = {' },
      { class: 'str', text: '            "Authorization"' },
      { class: '', text: ': f"Bearer {token}",' },
      { class: 'str', text: '            "Content-Type"' },
      { class: '', text: ': "application/scim+json"' },
      { class: '', text: '        }' },
      { class: '', text: '' },
      { class: '', text: '    def create_user(self, user_data: dict) -> dict:' },
      { class: '', text: '        resp = requests.post(' },
      { class: 'str', text: '            f"{self.base_url}/Users"' },
      { class: '', text: ',' },
      { class: '', text: '            headers=self.headers, json=user_data' },
      { class: '', text: '        )' },
      { class: '', text: '        resp.raise_for_status()' },
      { class: 'kw', text: '        return ' },
      { class: '', text: 'resp.json()' },
    ],
    run: [
      { class: 'mute', text: '$ python3 scim_client.py' },
      { class: 'info', text: 'POST /Users { "userName": "alice@org" }' },
      { class: 'ok', text: '201 Created // id: usr-a8f3c21' },
      { class: 'info', text: 'PATCH /Users/usr-a8f3c21 { "active": true }' },
      { class: 'ok', text: '200 OK // user activated' },
      { class: 'ok', text: 'SCIM provisioning complete' },
    ],
  },

  sql: {
    id: 'sql',
    name: 'SQL Query IDE', ext: '.sql', runLabel: '▷ EXECUTE', termLabel: 'QUERY_RESULTS',
    files: [
      { name: '// queries', section: true },
      { name: 'audit_log.sql', dot: 'g', active: true },
      { name: 'user_sessions.sql', dot: 'g' },
      { name: 'permissions.sql', dot: 'a' },
    ],
    code: [
      { class: 'cmt', text: '-- IAM Audit Log — failed auth events last 24h' },
      { class: '', text: '' },
      { class: 'kw', text: 'SELECT' },
      { class: '', text: '  e.event_id, e.timestamp,' },
      { class: '', text: '  u.email    AS user_email,' },
      { class: '', text: '  e.event_type, e.ip_address,' },
      { class: '', text: '  e.failure_reason' },
      { class: 'kw', text: 'FROM' },
      { class: '', text: '  audit_events e' },
      { class: 'kw', text: '  JOIN ' },
      { class: '', text: 'users u ON u.id = e.user_id' },
      { class: 'kw', text: 'WHERE' },
      { class: '', text: '  e.event_type IN (' },
      { class: 'str', text: "    'AUTH_FAILURE', 'MFA_FAILURE', 'LOCKOUT'" },
      { class: '', text: '  )' },
      { class: '', text: "  AND e.timestamp >= NOW() - INTERVAL " },
      { class: 'str', text: "'24 hours'" },
      { class: 'kw', text: 'ORDER BY' },
      { class: '', text: '  e.timestamp DESC' },
      { class: 'kw', text: 'LIMIT ' },
      { class: 'num', text: '100' },
      { class: '', text: ';' },
    ],
    run: [
      { class: 'mute', text: '$ psql -d iam_db -f audit_log.sql' },
      { class: 'mute', text: 'event_id | user_email        | event_type  | failure_reason' },
      { class: 'mute', text: '─────────┼──────────────────┼─────────────┼───────────────' },
      { class: 'err', text: 'e-0091   | bob@example.com  | MFA_FAILURE | invalid_totp' },
      { class: 'err', text: 'e-0088   | unknwn@evil.io   | AUTH_FAILURE| wrong_password' },
      { class: 'warn', text: 'e-0085   | carol@example.com| LOCKOUT     | 5_failed_attempts' },
      { class: 'mute', text: '(3 rows) // query time: 8ms' },
    ],
  },

  yaml: {
    id: 'yaml',
    name: 'YAML Editor', ext: '.yaml', runLabel: '▷ VALIDATE', termLabel: 'YAML_OUTPUT',
    files: [
      { name: '// manifests', section: true },
      { name: 'rbac.yaml', dot: 'g', active: true },
      { name: 'serviceaccount.yaml', dot: 'g' },
      { name: 'clusterrole.yaml', dot: 'a' },
    ],
    code: [
      { class: 'cmt', text: '# Kubernetes RBAC — Role + RoleBinding' },
      { class: 'kw', text: 'apiVersion' },
      { class: '', text: ': rbac.authorization.k8s.io/v1' },
      { class: 'kw', text: 'kind' },
      { class: '', text: ': Role' },
      { class: 'kw', text: 'metadata' },
      { class: '', text: ':' },
      { class: '', text: '  namespace: production' },
      { class: '', text: '  name: iam-reader' },
      { class: 'kw', text: 'rules' },
      { class: '', text: ':' },
      { class: '', text: '- apiGroups: [""]' },
      { class: '', text: '  resources: ["secrets", "configmaps"]' },
      { class: '', text: '  verbs: ["get", "list"]' },
      { class: '', text: '---' },
      { class: 'kw', text: 'apiVersion' },
      { class: '', text: ': rbac.authorization.k8s.io/v1' },
      { class: 'kw', text: 'kind' },
      { class: '', text: ': RoleBinding' },
      { class: 'kw', text: 'metadata' },
      { class: '', text: ':' },
      { class: '', text: '  name: iam-reader-binding' },
      { class: 'kw', text: 'subjects' },
      { class: '', text: ':' },
      { class: '', text: '- kind: ServiceAccount' },
      { class: '', text: '  name: iam-service' },
      { class: 'kw', text: 'roleRef' },
      { class: '', text: ':' },
      { class: '', text: '  kind: Role' },
      { class: '', text: '  name: iam-reader' },
    ],
    run: [
      { class: 'mute', text: '$ kubectl apply --dry-run=server -f rbac.yaml' },
      { class: 'ok', text: 'role.rbac/iam-reader configured (dry run)' },
      { class: 'ok', text: 'rolebinding.rbac/iam-reader-binding configured (dry run)' },
      { class: 'mute', text: '$ kubectl auth can-i list secrets --as=...iam-service -n production' },
      { class: 'ok', text: 'yes' },
    ],
  },

  bash: {
    id: 'bash',
    name: 'Bash / Shell IDE', ext: '.sh', runLabel: '▷ EXECUTE', termLabel: 'SHELL_OUTPUT',
    files: [
      { name: '// scripts', section: true },
      { name: 'token_inspect.sh', dot: 'g', active: true },
      { name: 'oauth_flow.sh', dot: 'g' },
      { name: 'cert_check.sh', dot: 'a' },
    ],
    code: [
      { class: 'cmt', text: '#!/usr/bin/env bash' },
      { class: 'cmt', text: '# OAuth 2.0 Token Inspector — decode + verify JWT' },
      { class: '', text: '' },
      { class: 'kw', text: 'TOKEN' },
      { class: '', text: '="${1:-$ACCESS_TOKEN}"' },
      { class: '', text: '' },
      { class: 'cmt', text: '# Split JWT into parts' },
      { class: 'kw', text: 'IFS' },
      { class: '', text: "='.' read -ra PARTS <<< \"$TOKEN\"" },
      { class: 'kw', text: 'HEADER' },
      { class: '', text: '=$(echo "${PARTS[0]}" | base64 -d | jq .)' },
      { class: 'kw', text: 'PAYLOAD' },
      { class: '', text: '=$(echo "${PARTS[1]}" | base64 -d | jq .)' },
      { class: '', text: '' },
      { class: 'kw', text: 'echo ' },
      { class: 'str', text: '"=== JWT HEADER ==="' },
      { class: 'kw', text: 'echo ' },
      { class: '', text: '$HEADER' },
      { class: 'kw', text: 'echo ' },
      { class: 'str', text: '"=== JWT PAYLOAD ==="' },
      { class: 'kw', text: 'echo ' },
      { class: '', text: '$PAYLOAD' },
      { class: '', text: '' },
      { class: 'cmt', text: '# Check expiry' },
      { class: 'kw', text: 'EXP' },
      { class: '', text: '=$(echo $PAYLOAD | jq .exp)' },
      { class: 'kw', text: 'NOW' },
      { class: '', text: '=$(date +%s)' },
      { class: 'kw', text: 'if ' },
      { class: '', text: '[[ $EXP -gt $NOW ]]; then' },
      { class: '', text: '  echo "✓ Token valid (expires in $((EXP-NOW))s)"' },
      { class: 'kw', text: 'else' },
      { class: '', text: '  echo "✗ Token EXPIRED"' },
      { class: 'kw', text: 'fi' },
    ],
    run: [
      { class: 'mute', text: '$ ./token_inspect.sh $ACCESS_TOKEN' },
      { class: 'mute', text: '=== JWT HEADER ===' },
      { class: 'ok', text: '{ "alg": "RS256", "typ": "JWT", "kid": "key-2025-01" }' },
      { class: 'mute', text: '=== JWT PAYLOAD ===' },
      { class: 'ok', text: '{ "sub": "alice@org", "exp": 1738003600, "amr": ["pwd","totp"] }' },
      { class: 'ok', text: '✓ Token valid (expires in 3196s)' },
    ],
  },

  typescript: {
    id: 'typescript',
    name: 'TypeScript IDE', ext: '.ts', runLabel: '▷ COMPILE + RUN', termLabel: 'TSC_OUTPUT',
    files: [
      { name: '// src', section: true },
      { name: 'token_validator.ts', dot: 'g', active: true },
      { name: 'jwks_client.ts', dot: 'g' },
      { name: '// types', section: true },
      { name: 'auth.d.ts', dot: 'a' },
    ],
    code: [
      { class: 'cmt', text: '// JWT Token Validator — TypeScript' },
      { class: '', text: '' },
      { class: 'kw', text: 'interface ' },
      { class: '', text: 'JWTClaims {' },
      { class: '', text: '  iss: string; sub: string;' },
      { class: '', text: '  aud: string | string[];' },
      { class: '', text: '  exp: number; iat: number;' },
      { class: '', text: '  amr?: string[];' },
      { class: '', text: '}' },
      { class: '', text: '' },
      { class: 'kw', text: 'async function ' },
      { class: '', text: 'validateToken(' },
      { class: '', text: '  token: string, expectedIssuer: string' },
      { class: '', text: '): Promise<JWTClaims> {' },
      { class: '', text: "  const [, payload] = token.split('.');" },
      { class: '', text: '  const claims: JWTClaims = JSON.parse(atob(payload));' },
      { class: '', text: '' },
      { class: '', text: '  if (claims.iss !== expectedIssuer)' },
      { class: 'kw', text: '    throw new ' },
      { class: '', text: 'Error("Invalid issuer");' },
      { class: '', text: '  if (Date.now() / 1000 > claims.exp)' },
      { class: 'kw', text: '    throw new ' },
      { class: '', text: 'Error("Token expired");' },
      { class: '', text: '' },
      { class: 'kw', text: '  return ' },
      { class: '', text: 'claims;' },
      { class: '', text: '}' },
    ],
    run: [
      { class: 'mute', text: '$ tsc --strict token_validator.ts && node token_validator.js' },
      { class: 'ok', text: '✓ TypeScript compilation PASS (strict mode)' },
      { class: 'ok', text: '✓ No type errors' },
      { class: 'ok', text: '✓ valid token → claims returned' },
      { class: 'err', text: '✗ expired token → Error: Token expired' },
      { class: 'err', text: '✗ wrong issuer → Error: Invalid issuer' },
      { class: 'ok', text: '3/3 test cases PASS' },
    ],
  },

  xacml: {
    id: 'xacml',
    name: 'XACML Policy IDE', ext: '.xml', runLabel: '▷ EVALUATE', termLabel: 'XACML_PDP_OUTPUT',
    files: [
      { name: '// policies', section: true },
      { name: 'policy.xml', dot: 'g', active: true },
      { name: 'policy-set.xml', dot: 'g' },
      { name: '// requests', section: true },
      { name: 'request.xml', dot: 'a' },
      { name: 'request-deny.xml', dot: 'r' },
    ],
    code: [
      { class: 'cmt', text: '<!-- XACML 3.0 Policy — Read Access to Production Data -->' },
      { class: '', text: '' },
      { class: 'kw', text: '<Policy PolicyId="prod-read-policy"' },
      { class: '', text: '       RuleCombiningAlgId=' },
      { class: 'str', text: '  "deny-overrides"' },
      { class: '', text: '>' },
      { class: 'kw', text: '  <Target><AnyOf><AllOf>' },
      { class: '', text: '    <Match MatchId="string-equal">' },
      { class: 'str', text: '      <AttributeValue>read</AttributeValue>' },
      { class: '', text: '      <AttributeDesignator Category="action"' },
      { class: 'str', text: '        AttributeId="action-id"/>' },
      { class: '', text: '    </Match>' },
      { class: 'kw', text: '  </AllOf></AnyOf></Target>' },
      { class: 'kw', text: '  <Rule RuleId="permit-engineers" Effect="Permit">' },
      { class: '', text: '    <Condition>mfa_verified AND in engineering_group</Condition>' },
      { class: 'kw', text: '  </Rule>' },
      { class: 'kw', text: '</Policy>' },
    ],
    run: [
      { class: 'mute', text: '$ xacml-pdp evaluate --policy policy.xml --request request.xml' },
      { class: 'ok', text: '✓ policy loaded: prod-read-policy' },
      { class: 'info', text: '⟳ evaluating request...' },
      { class: 'ok', text: 'Decision: PERMIT' },
      { class: 'ok', text: 'eval_time: 4ms' },
    ],
  },

  casbin: {
    id: 'casbin',
    name: 'Casbin DSL IDE', ext: '.conf', runLabel: '▷ ENFORCE', termLabel: 'CASBIN_OUTPUT',
    files: [
      { name: '// model', section: true },
      { name: 'rbac_model.conf', dot: 'g', active: true },
      { name: '// policies', section: true },
      { name: 'policy.csv', dot: 'a' },
      { name: '// tests', section: true },
      { name: 'test_cases.txt', dot: 'r' },
    ],
    code: [
      { class: 'cmt', text: '# Casbin RBAC Model — model.conf' },
      { class: '', text: '' },
      { class: 'kw', text: '[request_definition]' },
      { class: '', text: 'r = sub, obj, act' },
      { class: '', text: '' },
      { class: 'kw', text: '[policy_definition]' },
      { class: '', text: 'p = sub, obj, act' },
      { class: '', text: '' },
      { class: 'kw', text: '[role_definition]' },
      { class: '', text: 'g = _, _' },
      { class: '', text: '' },
      { class: 'kw', text: '[policy_effect]' },
      { class: 'str', text: 'e = some(where (p.eft == allow))' },
      { class: '', text: '' },
      { class: 'kw', text: '[matchers]' },
      { class: 'str', text: 'm = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act' },
      { class: '', text: '' },
      { class: 'cmt', text: '# policy.csv' },
      { class: '', text: 'p, admin, /data, read' },
      { class: '', text: 'p, admin, /data, write' },
      { class: '', text: 'p, analyst, /data, read' },
      { class: '', text: 'g, alice, admin' },
      { class: '', text: 'g, bob, analyst' },
    ],
    run: [
      { class: 'mute', text: '$ casbin enforce --model rbac_model.conf --policy policy.csv' },
      { class: 'ok', text: 'enforce(alice, /data, read)  → true' },
      { class: 'ok', text: 'enforce(alice, /data, write) → true' },
      { class: 'ok', text: 'enforce(bob,   /data, read)  → true' },
      { class: 'err', text: 'enforce(bob,   /data, write) → false (no write for analyst)' },
      { class: 'ok', text: '4/4 assertions complete' },
    ],
  },

  graphql: {
    id: 'graphql',
    name: 'GraphQL IDE', ext: '.graphql', runLabel: '▷ QUERY', termLabel: 'GQL_RESPONSE',
    files: [
      { name: '// queries', section: true },
      { name: 'user_perms.graphql', dot: 'g', active: true },
      { name: 'roles.graphql', dot: 'g' },
      { name: '// schema', section: true },
      { name: 'schema.graphql', dot: 'a' },
    ],
    code: [
      { class: 'cmt', text: '# GraphQL — Query user permissions + active sessions' },
      { class: '', text: '' },
      { class: 'kw', text: 'query ' },
      { class: '', text: 'UserPermissions($userId: ID!) {' },
      { class: '', text: '  user(id: $userId) {' },
      { class: '', text: '    id' },
      { class: '', text: '    email' },
      { class: '', text: '    roles {' },
      { class: '', text: '      name' },
      { class: '', text: '      permissions { resource actions }' },
      { class: '', text: '    }' },
      { class: '', text: '    activeSessions {' },
      { class: '', text: '      sessionId' },
      { class: '', text: '      createdAt' },
      { class: '', text: '      ipAddress' },
      { class: '', text: '      mfaVerified' },
      { class: '', text: '    }' },
      { class: '', text: '  }' },
      { class: '', text: '}' },
      { class: '', text: '' },
      { class: 'cmt', text: '# Variables: { "userId": "usr-a8f3c21" }' },
    ],
    run: [
      { class: 'mute', text: 'POST /graphql HTTP/1.1  Authorization: Bearer <token>' },
      { class: 'ok', text: 'HTTP/1.1 200 OK' },
      { class: 'ok', text: '{ "data": { "user": {' },
      { class: 'ok', text: '    "email": "alice@org",' },
      { class: 'ok', text: '    "roles": [{ "name": "iam-admin", "permissions": [...] }],' },
      { class: 'ok', text: '    "activeSessions": [{ "sessionId": "s-x7k2", "mfaVerified": true }]' },
      { class: 'ok', text: '  }}}' },
    ],
  },

  xml: {
    id: 'xml',
    name: 'XML / SAML Editor', ext: '.xml', runLabel: '▷ VALIDATE', termLabel: 'XML_OUTPUT',
    files: [
      { name: '// saml', section: true },
      { name: 'saml_response.xml', dot: 'g', active: true },
      { name: 'authn_request.xml', dot: 'a' },
      { name: 'metadata.xml', dot: 'a' },
    ],
    code: [
      { class: 'cmt', text: '<!-- SAML 2.0 AuthnRequest (SP-Initiated) -->' },
      { class: 'kw', text: '<samlp:AuthnRequest' },
      { class: '', text: '  xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"' },
      { class: '', text: '  ID="_abc123def456"' },
      { class: '', text: '  Version="2.0"' },
      { class: 'str', text: '  AssertionConsumerServiceURL="https://app.example.com/saml/acs"' },
      { class: 'str', text: '  Destination="https://idp.example.com/sso"' },
      { class: '', text: '>' },
      { class: 'kw', text: '  <saml:Issuer>' },
      { class: 'str', text: '    https://app.example.com/sp' },
      { class: 'kw', text: '  </saml:Issuer>' },
      { class: 'kw', text: '  <samlp:NameIDPolicy' },
      { class: 'str', text: '    Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"' },
      { class: '', text: '    AllowCreate="true"/>' },
      { class: 'kw', text: '</samlp:AuthnRequest>' },
    ],
    run: [
      { class: 'mute', text: '$ saml-validator --validate saml_response.xml --cert idp_cert.pem' },
      { class: 'ok', text: '✓ well-formed XML' },
      { class: 'ok', text: '✓ SAML 2.0 schema validated' },
      { class: 'ok', text: '✓ signature valid (RSA-SHA256)' },
      { class: 'ok', text: '✓ NotBefore / NotOnOrAfter within tolerance' },
      { class: 'ok', text: 'validation PASS' },
    ],
  },

  toml: {
    id: 'toml',
    name: 'TOML Config Editor', ext: '.toml', runLabel: '▷ VALIDATE', termLabel: 'TOML_OUTPUT',
    files: [
      { name: '// configs', section: true },
      { name: 'auth_server.toml', dot: 'g', active: true },
      { name: 'idp.toml', dot: 'a' },
    ],
    code: [
      { class: 'cmt', text: '# Auth Server Configuration' },
      { class: '', text: '' },
      { class: 'kw', text: '[server]' },
      { class: '', text: 'host = "0.0.0.0"' },
      { class: 'num', text: 'port = 8443' },
      { class: '', text: 'tls_cert = "./certs/server.pem"' },
      { class: '', text: '' },
      { class: 'kw', text: '[oidc]' },
      { class: '', text: 'issuer = "https://auth.example.com"' },
      { class: 'num', text: 'access_token_ttl = 3600' },
      { class: 'num', text: 'refresh_token_ttl = 86400' },
      { class: 'kw', text: 'rotate_refresh_tokens = true' },
      { class: '', text: '' },
      { class: 'kw', text: '[clients.my-app]' },
      { class: '', text: 'client_id = "my-app-client-001"' },
      { class: '', text: 'redirect_uris = ["https://app.example.com/cb"]' },
      { class: '', text: 'grant_types = ["authorization_code", "refresh_token"]' },
      { class: 'kw', text: 'pkce_required = true' },
    ],
    run: [
      { class: 'mute', text: '$ auth-server validate --config auth_server.toml' },
      { class: 'ok', text: '✓ TOML syntax valid' },
      { class: 'ok', text: '✓ issuer is HTTPS' },
      { class: 'ok', text: '✓ pkce_required = true ✓' },
      { class: 'warn', text: '⚠  refresh_token_ttl > 24h — review rotation policy' },
      { class: 'ok', text: 'config validation PASS // 1 warning' },
    ],
  },

  ldap: {
    id: 'ldap',
    name: 'LDAP Filter IDE', ext: '.ldap', runLabel: '▷ SEARCH', termLabel: 'LDAP_RESULTS',
    files: [
      { name: '// filters', section: true },
      { name: 'user_lookup.ldap', dot: 'g', active: true },
      { name: 'group_members.ldap', dot: 'g' },
      { name: 'admin_accounts.ldap', dot: 'r' },
    ],
    code: [
      { class: 'cmt', text: '# LDAP Search — IAM team members with MFA enrolled' },
      { class: 'cmt', text: '# Base DN: ou=People,dc=example,dc=com' },
      { class: '', text: '' },
      { class: 'cmt', text: '# Filter: MFA enrolled + account enabled' },
      { class: 'kw', text: '(& ' },
      { class: '', text: '  (objectClass=person)' },
      { class: '', text: '  (memberOf=CN=iam-team,OU=Groups,DC=example,DC=com)' },
      { class: '', text: '  (mfaEnrolled=TRUE)' },
      { class: '', text: '  (!(userAccountControl:1.2.840.113556.1.4.803:=2))' },
      { class: '', text: ')' },
      { class: '', text: '' },
      { class: 'cmt', text: '# Find users with password older than 90 days' },
      { class: 'kw', text: '(& ' },
      { class: '', text: '  (objectClass=user)' },
      { class: '', text: '  (pwdLastSet<=132800000000000000)' },
      { class: '', text: '  (!(userAccountControl:1.2.840.113556.1.4.803:=2))' },
      { class: '', text: ')' },
    ],
    run: [
      { class: 'mute', text: '$ ldapsearch -H ldap://dc.example.com -x -b "ou=People,..."' },
      { class: 'ok', text: 'cn: Alice Kim | mail: alice@example.com | mfaEnrolled: TRUE' },
      { class: 'ok', text: 'cn: Bob Chen  | mail: bob@example.com  | mfaEnrolled: TRUE' },
      { class: 'mute', text: '# numResponses: 2' },
      { class: 'ok', text: 'search complete' },
    ],
  },

  jmespath: {
    id: 'jmespath',
    name: 'JMESPath IDE', ext: '.jmespath', runLabel: '▷ QUERY', termLabel: 'JMESPATH_OUTPUT',
    files: [
      { name: '// expressions', section: true },
      { name: 'jwt_claims.jmespath', dot: 'g', active: true },
      { name: 'iam_policy.jmespath', dot: 'g' },
      { name: '// data', section: true },
      { name: 'payload.json', dot: 'a' },
    ],
    code: [
      { class: 'cmt', text: '# JMESPath — Extract + transform JWT claims' },
      { class: 'cmt', text: '# Input: decoded JWT payload JSON' },
      { class: '', text: '' },
      { class: 'cmt', text: '# 1. Get all group memberships' },
      { class: 'str', text: 'groups' },
      { class: '', text: '' },
      { class: 'cmt', text: "# 2. Check engineering membership" },
      { class: 'str', text: "contains(groups, 'engineering')" },
      { class: '', text: '' },
      { class: 'cmt', text: '# 3. Extract email domain' },
      { class: 'str', text: "split(email, '@')[1]" },
      { class: '', text: '' },
      { class: 'cmt', text: '# 4. Filter sessions where mfaVerified is true' },
      { class: 'str', text: 'activeSessions[?mfaVerified==`true`]' },
      { class: '', text: '' },
      { class: 'cmt', text: '# 5. Get Allow statement resources from IAM policy' },
      { class: 'str', text: 'Statement[?Effect==`Allow`].Resource[]' },
      { class: '', text: '' },
      { class: 'cmt', text: '# 6. Summary projection' },
      { class: 'str', text: '{email: email, roles: groups, expires: exp}' },
    ],
    run: [
      { class: 'mute', text: '$ jp -f payload.json "groups"' },
      { class: 'ok', text: '["engineering", "iam-admins"]' },
      { class: 'mute', text: "$ jp -f payload.json \"contains(groups, 'engineering')\"" },
      { class: 'ok', text: 'true' },
      { class: 'mute', text: "$ jp -f payload.json \"split(email, '@')[1]\"" },
      { class: 'ok', text: '"example.org"' },
      { class: 'mute', text: '$ jp -f payload.json "activeSessions[?mfaVerified==`true`]"' },
      { class: 'ok', text: '[{ "sessionId": "s-x7k2", "mfaVerified": true }]' },
      { class: 'ok', text: '4/4 queries complete' },
    ],
  },
}

export const allLangIds = Object.keys(langDataMap)
